// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zkp.proto

#ifndef PROTOBUF_INCLUDED_zkp_2eproto
#define PROTOBUF_INCLUDED_zkp_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "crypto-curve/curve_point.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_zkp_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_zkp_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_zkp_2eproto();
namespace safeheron {
namespace proto {
class AliceRangeProof;
class AliceRangeProofDefaultTypeInternal;
extern AliceRangeProofDefaultTypeInternal _AliceRangeProof_default_instance_;
class DLNProof;
class DLNProofDefaultTypeInternal;
extern DLNProofDefaultTypeInternal _DLNProof_default_instance_;
class DLogProof;
class DLogProofDefaultTypeInternal;
extern DLogProofDefaultTypeInternal _DLogProof_default_instance_;
class HegProof;
class HegProofDefaultTypeInternal;
extern HegProofDefaultTypeInternal _HegProof_default_instance_;
class PailProof;
class PailProofDefaultTypeInternal;
extern PailProofDefaultTypeInternal _PailProof_default_instance_;
}  // namespace proto
}  // namespace safeheron
namespace google {
namespace protobuf {
template<> ::safeheron::proto::AliceRangeProof* Arena::CreateMaybeMessage<::safeheron::proto::AliceRangeProof>(Arena*);
template<> ::safeheron::proto::DLNProof* Arena::CreateMaybeMessage<::safeheron::proto::DLNProof>(Arena*);
template<> ::safeheron::proto::DLogProof* Arena::CreateMaybeMessage<::safeheron::proto::DLogProof>(Arena*);
template<> ::safeheron::proto::HegProof* Arena::CreateMaybeMessage<::safeheron::proto::HegProof>(Arena*);
template<> ::safeheron::proto::PailProof* Arena::CreateMaybeMessage<::safeheron::proto::PailProof>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace safeheron {
namespace proto {

// ===================================================================

class DLogProof :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.DLogProof) */ {
 public:
  DLogProof();
  virtual ~DLogProof();

  DLogProof(const DLogProof& from);

  inline DLogProof& operator=(const DLogProof& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DLogProof(DLogProof&& from) noexcept
    : DLogProof() {
    *this = ::std::move(from);
  }

  inline DLogProof& operator=(DLogProof&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DLogProof& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DLogProof* internal_default_instance() {
    return reinterpret_cast<const DLogProof*>(
               &_DLogProof_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DLogProof* other);
  friend void swap(DLogProof& a, DLogProof& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DLogProof* New() const final {
    return CreateMaybeMessage<DLogProof>(nullptr);
  }

  DLogProof* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DLogProof>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DLogProof& from);
  void MergeFrom(const DLogProof& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DLogProof* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string res = 3;
  void clear_res();
  static const int kResFieldNumber = 3;
  const ::std::string& res() const;
  void set_res(const ::std::string& value);
  #if LANG_CXX11
  void set_res(::std::string&& value);
  #endif
  void set_res(const char* value);
  void set_res(const char* value, size_t size);
  ::std::string* mutable_res();
  ::std::string* release_res();
  void set_allocated_res(::std::string* res);

  // .safeheron.proto.CurvePoint pk = 1;
  bool has_pk() const;
  void clear_pk();
  static const int kPkFieldNumber = 1;
  const ::safeheron::proto::CurvePoint& pk() const;
  ::safeheron::proto::CurvePoint* release_pk();
  ::safeheron::proto::CurvePoint* mutable_pk();
  void set_allocated_pk(::safeheron::proto::CurvePoint* pk);

  // .safeheron.proto.CurvePoint g_r = 2;
  bool has_g_r() const;
  void clear_g_r();
  static const int kGRFieldNumber = 2;
  const ::safeheron::proto::CurvePoint& g_r() const;
  ::safeheron::proto::CurvePoint* release_g_r();
  ::safeheron::proto::CurvePoint* mutable_g_r();
  void set_allocated_g_r(::safeheron::proto::CurvePoint* g_r);

  // @@protoc_insertion_point(class_scope:safeheron.proto.DLogProof)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr res_;
  ::safeheron::proto::CurvePoint* pk_;
  ::safeheron::proto::CurvePoint* g_r_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_zkp_2eproto;
};
// -------------------------------------------------------------------

class HegProof :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.HegProof) */ {
 public:
  HegProof();
  virtual ~HegProof();

  HegProof(const HegProof& from);

  inline HegProof& operator=(const HegProof& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HegProof(HegProof&& from) noexcept
    : HegProof() {
    *this = ::std::move(from);
  }

  inline HegProof& operator=(HegProof&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const HegProof& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HegProof* internal_default_instance() {
    return reinterpret_cast<const HegProof*>(
               &_HegProof_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(HegProof* other);
  friend void swap(HegProof& a, HegProof& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HegProof* New() const final {
    return CreateMaybeMessage<HegProof>(nullptr);
  }

  HegProof* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HegProof>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HegProof& from);
  void MergeFrom(const HegProof& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HegProof* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string z1 = 3;
  void clear_z1();
  static const int kZ1FieldNumber = 3;
  const ::std::string& z1() const;
  void set_z1(const ::std::string& value);
  #if LANG_CXX11
  void set_z1(::std::string&& value);
  #endif
  void set_z1(const char* value);
  void set_z1(const char* value, size_t size);
  ::std::string* mutable_z1();
  ::std::string* release_z1();
  void set_allocated_z1(::std::string* z1);

  // string z2 = 4;
  void clear_z2();
  static const int kZ2FieldNumber = 4;
  const ::std::string& z2() const;
  void set_z2(const ::std::string& value);
  #if LANG_CXX11
  void set_z2(::std::string&& value);
  #endif
  void set_z2(const char* value);
  void set_z2(const char* value, size_t size);
  ::std::string* mutable_z2();
  ::std::string* release_z2();
  void set_allocated_z2(::std::string* z2);

  // .safeheron.proto.CurvePoint T = 1;
  bool has_t() const;
  void clear_t();
  static const int kTFieldNumber = 1;
  const ::safeheron::proto::CurvePoint& t() const;
  ::safeheron::proto::CurvePoint* release_t();
  ::safeheron::proto::CurvePoint* mutable_t();
  void set_allocated_t(::safeheron::proto::CurvePoint* t);

  // .safeheron.proto.CurvePoint A3 = 2;
  bool has_a3() const;
  void clear_a3();
  static const int kA3FieldNumber = 2;
  const ::safeheron::proto::CurvePoint& a3() const;
  ::safeheron::proto::CurvePoint* release_a3();
  ::safeheron::proto::CurvePoint* mutable_a3();
  void set_allocated_a3(::safeheron::proto::CurvePoint* a3);

  // @@protoc_insertion_point(class_scope:safeheron.proto.HegProof)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr z1_;
  ::google::protobuf::internal::ArenaStringPtr z2_;
  ::safeheron::proto::CurvePoint* t_;
  ::safeheron::proto::CurvePoint* a3_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_zkp_2eproto;
};
// -------------------------------------------------------------------

class PailProof :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.PailProof) */ {
 public:
  PailProof();
  virtual ~PailProof();

  PailProof(const PailProof& from);

  inline PailProof& operator=(const PailProof& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PailProof(PailProof&& from) noexcept
    : PailProof() {
    *this = ::std::move(from);
  }

  inline PailProof& operator=(PailProof&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PailProof& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PailProof* internal_default_instance() {
    return reinterpret_cast<const PailProof*>(
               &_PailProof_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(PailProof* other);
  friend void swap(PailProof& a, PailProof& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PailProof* New() const final {
    return CreateMaybeMessage<PailProof>(nullptr);
  }

  PailProof* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PailProof>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PailProof& from);
  void MergeFrom(const PailProof& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PailProof* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string y_N_arr = 1;
  int y_n_arr_size() const;
  void clear_y_n_arr();
  static const int kYNArrFieldNumber = 1;
  const ::std::string& y_n_arr(int index) const;
  ::std::string* mutable_y_n_arr(int index);
  void set_y_n_arr(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_y_n_arr(int index, ::std::string&& value);
  #endif
  void set_y_n_arr(int index, const char* value);
  void set_y_n_arr(int index, const char* value, size_t size);
  ::std::string* add_y_n_arr();
  void add_y_n_arr(const ::std::string& value);
  #if LANG_CXX11
  void add_y_n_arr(::std::string&& value);
  #endif
  void add_y_n_arr(const char* value);
  void add_y_n_arr(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField<::std::string>& y_n_arr() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* mutable_y_n_arr();

  // @@protoc_insertion_point(class_scope:safeheron.proto.PailProof)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField<::std::string> y_n_arr_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_zkp_2eproto;
};
// -------------------------------------------------------------------

class AliceRangeProof :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.AliceRangeProof) */ {
 public:
  AliceRangeProof();
  virtual ~AliceRangeProof();

  AliceRangeProof(const AliceRangeProof& from);

  inline AliceRangeProof& operator=(const AliceRangeProof& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AliceRangeProof(AliceRangeProof&& from) noexcept
    : AliceRangeProof() {
    *this = ::std::move(from);
  }

  inline AliceRangeProof& operator=(AliceRangeProof&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const AliceRangeProof& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AliceRangeProof* internal_default_instance() {
    return reinterpret_cast<const AliceRangeProof*>(
               &_AliceRangeProof_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(AliceRangeProof* other);
  friend void swap(AliceRangeProof& a, AliceRangeProof& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AliceRangeProof* New() const final {
    return CreateMaybeMessage<AliceRangeProof>(nullptr);
  }

  AliceRangeProof* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AliceRangeProof>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AliceRangeProof& from);
  void MergeFrom(const AliceRangeProof& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AliceRangeProof* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string z = 1;
  void clear_z();
  static const int kZFieldNumber = 1;
  const ::std::string& z() const;
  void set_z(const ::std::string& value);
  #if LANG_CXX11
  void set_z(::std::string&& value);
  #endif
  void set_z(const char* value);
  void set_z(const char* value, size_t size);
  ::std::string* mutable_z();
  ::std::string* release_z();
  void set_allocated_z(::std::string* z);

  // string u = 2;
  void clear_u();
  static const int kUFieldNumber = 2;
  const ::std::string& u() const;
  void set_u(const ::std::string& value);
  #if LANG_CXX11
  void set_u(::std::string&& value);
  #endif
  void set_u(const char* value);
  void set_u(const char* value, size_t size);
  ::std::string* mutable_u();
  ::std::string* release_u();
  void set_allocated_u(::std::string* u);

  // string w = 3;
  void clear_w();
  static const int kWFieldNumber = 3;
  const ::std::string& w() const;
  void set_w(const ::std::string& value);
  #if LANG_CXX11
  void set_w(::std::string&& value);
  #endif
  void set_w(const char* value);
  void set_w(const char* value, size_t size);
  ::std::string* mutable_w();
  ::std::string* release_w();
  void set_allocated_w(::std::string* w);

  // string s = 4;
  void clear_s();
  static const int kSFieldNumber = 4;
  const ::std::string& s() const;
  void set_s(const ::std::string& value);
  #if LANG_CXX11
  void set_s(::std::string&& value);
  #endif
  void set_s(const char* value);
  void set_s(const char* value, size_t size);
  ::std::string* mutable_s();
  ::std::string* release_s();
  void set_allocated_s(::std::string* s);

  // string s1 = 5;
  void clear_s1();
  static const int kS1FieldNumber = 5;
  const ::std::string& s1() const;
  void set_s1(const ::std::string& value);
  #if LANG_CXX11
  void set_s1(::std::string&& value);
  #endif
  void set_s1(const char* value);
  void set_s1(const char* value, size_t size);
  ::std::string* mutable_s1();
  ::std::string* release_s1();
  void set_allocated_s1(::std::string* s1);

  // string s2 = 6;
  void clear_s2();
  static const int kS2FieldNumber = 6;
  const ::std::string& s2() const;
  void set_s2(const ::std::string& value);
  #if LANG_CXX11
  void set_s2(::std::string&& value);
  #endif
  void set_s2(const char* value);
  void set_s2(const char* value, size_t size);
  ::std::string* mutable_s2();
  ::std::string* release_s2();
  void set_allocated_s2(::std::string* s2);

  // @@protoc_insertion_point(class_scope:safeheron.proto.AliceRangeProof)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr z_;
  ::google::protobuf::internal::ArenaStringPtr u_;
  ::google::protobuf::internal::ArenaStringPtr w_;
  ::google::protobuf::internal::ArenaStringPtr s_;
  ::google::protobuf::internal::ArenaStringPtr s1_;
  ::google::protobuf::internal::ArenaStringPtr s2_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_zkp_2eproto;
};
// -------------------------------------------------------------------

class DLNProof :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.DLNProof) */ {
 public:
  DLNProof();
  virtual ~DLNProof();

  DLNProof(const DLNProof& from);

  inline DLNProof& operator=(const DLNProof& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DLNProof(DLNProof&& from) noexcept
    : DLNProof() {
    *this = ::std::move(from);
  }

  inline DLNProof& operator=(DLNProof&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DLNProof& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DLNProof* internal_default_instance() {
    return reinterpret_cast<const DLNProof*>(
               &_DLNProof_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(DLNProof* other);
  friend void swap(DLNProof& a, DLNProof& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DLNProof* New() const final {
    return CreateMaybeMessage<DLNProof>(nullptr);
  }

  DLNProof* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DLNProof>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DLNProof& from);
  void MergeFrom(const DLNProof& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DLNProof* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string alpha_arr = 1;
  int alpha_arr_size() const;
  void clear_alpha_arr();
  static const int kAlphaArrFieldNumber = 1;
  const ::std::string& alpha_arr(int index) const;
  ::std::string* mutable_alpha_arr(int index);
  void set_alpha_arr(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_alpha_arr(int index, ::std::string&& value);
  #endif
  void set_alpha_arr(int index, const char* value);
  void set_alpha_arr(int index, const char* value, size_t size);
  ::std::string* add_alpha_arr();
  void add_alpha_arr(const ::std::string& value);
  #if LANG_CXX11
  void add_alpha_arr(::std::string&& value);
  #endif
  void add_alpha_arr(const char* value);
  void add_alpha_arr(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField<::std::string>& alpha_arr() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* mutable_alpha_arr();

  // repeated string t_arr = 2;
  int t_arr_size() const;
  void clear_t_arr();
  static const int kTArrFieldNumber = 2;
  const ::std::string& t_arr(int index) const;
  ::std::string* mutable_t_arr(int index);
  void set_t_arr(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_t_arr(int index, ::std::string&& value);
  #endif
  void set_t_arr(int index, const char* value);
  void set_t_arr(int index, const char* value, size_t size);
  ::std::string* add_t_arr();
  void add_t_arr(const ::std::string& value);
  #if LANG_CXX11
  void add_t_arr(::std::string&& value);
  #endif
  void add_t_arr(const char* value);
  void add_t_arr(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField<::std::string>& t_arr() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* mutable_t_arr();

  // @@protoc_insertion_point(class_scope:safeheron.proto.DLNProof)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField<::std::string> alpha_arr_;
  ::google::protobuf::RepeatedPtrField<::std::string> t_arr_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_zkp_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DLogProof

// .safeheron.proto.CurvePoint pk = 1;
inline bool DLogProof::has_pk() const {
  return this != internal_default_instance() && pk_ != nullptr;
}
inline const ::safeheron::proto::CurvePoint& DLogProof::pk() const {
  const ::safeheron::proto::CurvePoint* p = pk_;
  // @@protoc_insertion_point(field_get:safeheron.proto.DLogProof.pk)
  return p != nullptr ? *p : *reinterpret_cast<const ::safeheron::proto::CurvePoint*>(
      &::safeheron::proto::_CurvePoint_default_instance_);
}
inline ::safeheron::proto::CurvePoint* DLogProof::release_pk() {
  // @@protoc_insertion_point(field_release:safeheron.proto.DLogProof.pk)
  
  ::safeheron::proto::CurvePoint* temp = pk_;
  pk_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* DLogProof::mutable_pk() {
  
  if (pk_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArenaNoVirtual());
    pk_ = p;
  }
  // @@protoc_insertion_point(field_mutable:safeheron.proto.DLogProof.pk)
  return pk_;
}
inline void DLogProof::set_allocated_pk(::safeheron::proto::CurvePoint* pk) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(pk_);
  }
  if (pk) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      pk = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pk, submessage_arena);
    }
    
  } else {
    
  }
  pk_ = pk;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.DLogProof.pk)
}

// .safeheron.proto.CurvePoint g_r = 2;
inline bool DLogProof::has_g_r() const {
  return this != internal_default_instance() && g_r_ != nullptr;
}
inline const ::safeheron::proto::CurvePoint& DLogProof::g_r() const {
  const ::safeheron::proto::CurvePoint* p = g_r_;
  // @@protoc_insertion_point(field_get:safeheron.proto.DLogProof.g_r)
  return p != nullptr ? *p : *reinterpret_cast<const ::safeheron::proto::CurvePoint*>(
      &::safeheron::proto::_CurvePoint_default_instance_);
}
inline ::safeheron::proto::CurvePoint* DLogProof::release_g_r() {
  // @@protoc_insertion_point(field_release:safeheron.proto.DLogProof.g_r)
  
  ::safeheron::proto::CurvePoint* temp = g_r_;
  g_r_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* DLogProof::mutable_g_r() {
  
  if (g_r_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArenaNoVirtual());
    g_r_ = p;
  }
  // @@protoc_insertion_point(field_mutable:safeheron.proto.DLogProof.g_r)
  return g_r_;
}
inline void DLogProof::set_allocated_g_r(::safeheron::proto::CurvePoint* g_r) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(g_r_);
  }
  if (g_r) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      g_r = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, g_r, submessage_arena);
    }
    
  } else {
    
  }
  g_r_ = g_r;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.DLogProof.g_r)
}

// string res = 3;
inline void DLogProof::clear_res() {
  res_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DLogProof::res() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.DLogProof.res)
  return res_.GetNoArena();
}
inline void DLogProof::set_res(const ::std::string& value) {
  
  res_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.DLogProof.res)
}
#if LANG_CXX11
inline void DLogProof::set_res(::std::string&& value) {
  
  res_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.DLogProof.res)
}
#endif
inline void DLogProof::set_res(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  res_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.DLogProof.res)
}
inline void DLogProof::set_res(const char* value, size_t size) {
  
  res_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.DLogProof.res)
}
inline ::std::string* DLogProof::mutable_res() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.DLogProof.res)
  return res_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DLogProof::release_res() {
  // @@protoc_insertion_point(field_release:safeheron.proto.DLogProof.res)
  
  return res_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DLogProof::set_allocated_res(::std::string* res) {
  if (res != nullptr) {
    
  } else {
    
  }
  res_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), res);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.DLogProof.res)
}

// -------------------------------------------------------------------

// HegProof

// .safeheron.proto.CurvePoint T = 1;
inline bool HegProof::has_t() const {
  return this != internal_default_instance() && t_ != nullptr;
}
inline const ::safeheron::proto::CurvePoint& HegProof::t() const {
  const ::safeheron::proto::CurvePoint* p = t_;
  // @@protoc_insertion_point(field_get:safeheron.proto.HegProof.T)
  return p != nullptr ? *p : *reinterpret_cast<const ::safeheron::proto::CurvePoint*>(
      &::safeheron::proto::_CurvePoint_default_instance_);
}
inline ::safeheron::proto::CurvePoint* HegProof::release_t() {
  // @@protoc_insertion_point(field_release:safeheron.proto.HegProof.T)
  
  ::safeheron::proto::CurvePoint* temp = t_;
  t_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* HegProof::mutable_t() {
  
  if (t_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArenaNoVirtual());
    t_ = p;
  }
  // @@protoc_insertion_point(field_mutable:safeheron.proto.HegProof.T)
  return t_;
}
inline void HegProof::set_allocated_t(::safeheron::proto::CurvePoint* t) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(t_);
  }
  if (t) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      t = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, t, submessage_arena);
    }
    
  } else {
    
  }
  t_ = t;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.HegProof.T)
}

// .safeheron.proto.CurvePoint A3 = 2;
inline bool HegProof::has_a3() const {
  return this != internal_default_instance() && a3_ != nullptr;
}
inline const ::safeheron::proto::CurvePoint& HegProof::a3() const {
  const ::safeheron::proto::CurvePoint* p = a3_;
  // @@protoc_insertion_point(field_get:safeheron.proto.HegProof.A3)
  return p != nullptr ? *p : *reinterpret_cast<const ::safeheron::proto::CurvePoint*>(
      &::safeheron::proto::_CurvePoint_default_instance_);
}
inline ::safeheron::proto::CurvePoint* HegProof::release_a3() {
  // @@protoc_insertion_point(field_release:safeheron.proto.HegProof.A3)
  
  ::safeheron::proto::CurvePoint* temp = a3_;
  a3_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* HegProof::mutable_a3() {
  
  if (a3_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArenaNoVirtual());
    a3_ = p;
  }
  // @@protoc_insertion_point(field_mutable:safeheron.proto.HegProof.A3)
  return a3_;
}
inline void HegProof::set_allocated_a3(::safeheron::proto::CurvePoint* a3) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(a3_);
  }
  if (a3) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      a3 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, a3, submessage_arena);
    }
    
  } else {
    
  }
  a3_ = a3;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.HegProof.A3)
}

// string z1 = 3;
inline void HegProof::clear_z1() {
  z1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HegProof::z1() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.HegProof.z1)
  return z1_.GetNoArena();
}
inline void HegProof::set_z1(const ::std::string& value) {
  
  z1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.HegProof.z1)
}
#if LANG_CXX11
inline void HegProof::set_z1(::std::string&& value) {
  
  z1_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.HegProof.z1)
}
#endif
inline void HegProof::set_z1(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  z1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.HegProof.z1)
}
inline void HegProof::set_z1(const char* value, size_t size) {
  
  z1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.HegProof.z1)
}
inline ::std::string* HegProof::mutable_z1() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.HegProof.z1)
  return z1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HegProof::release_z1() {
  // @@protoc_insertion_point(field_release:safeheron.proto.HegProof.z1)
  
  return z1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HegProof::set_allocated_z1(::std::string* z1) {
  if (z1 != nullptr) {
    
  } else {
    
  }
  z1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), z1);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.HegProof.z1)
}

// string z2 = 4;
inline void HegProof::clear_z2() {
  z2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HegProof::z2() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.HegProof.z2)
  return z2_.GetNoArena();
}
inline void HegProof::set_z2(const ::std::string& value) {
  
  z2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.HegProof.z2)
}
#if LANG_CXX11
inline void HegProof::set_z2(::std::string&& value) {
  
  z2_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.HegProof.z2)
}
#endif
inline void HegProof::set_z2(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  z2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.HegProof.z2)
}
inline void HegProof::set_z2(const char* value, size_t size) {
  
  z2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.HegProof.z2)
}
inline ::std::string* HegProof::mutable_z2() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.HegProof.z2)
  return z2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HegProof::release_z2() {
  // @@protoc_insertion_point(field_release:safeheron.proto.HegProof.z2)
  
  return z2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HegProof::set_allocated_z2(::std::string* z2) {
  if (z2 != nullptr) {
    
  } else {
    
  }
  z2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), z2);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.HegProof.z2)
}

// -------------------------------------------------------------------

// PailProof

// repeated string y_N_arr = 1;
inline int PailProof::y_n_arr_size() const {
  return y_n_arr_.size();
}
inline void PailProof::clear_y_n_arr() {
  y_n_arr_.Clear();
}
inline const ::std::string& PailProof::y_n_arr(int index) const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailProof.y_N_arr)
  return y_n_arr_.Get(index);
}
inline ::std::string* PailProof::mutable_y_n_arr(int index) {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailProof.y_N_arr)
  return y_n_arr_.Mutable(index);
}
inline void PailProof::set_y_n_arr(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:safeheron.proto.PailProof.y_N_arr)
  y_n_arr_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void PailProof::set_y_n_arr(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:safeheron.proto.PailProof.y_N_arr)
  y_n_arr_.Mutable(index)->assign(std::move(value));
}
#endif
inline void PailProof::set_y_n_arr(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  y_n_arr_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:safeheron.proto.PailProof.y_N_arr)
}
inline void PailProof::set_y_n_arr(int index, const char* value, size_t size) {
  y_n_arr_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.PailProof.y_N_arr)
}
inline ::std::string* PailProof::add_y_n_arr() {
  // @@protoc_insertion_point(field_add_mutable:safeheron.proto.PailProof.y_N_arr)
  return y_n_arr_.Add();
}
inline void PailProof::add_y_n_arr(const ::std::string& value) {
  y_n_arr_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:safeheron.proto.PailProof.y_N_arr)
}
#if LANG_CXX11
inline void PailProof::add_y_n_arr(::std::string&& value) {
  y_n_arr_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:safeheron.proto.PailProof.y_N_arr)
}
#endif
inline void PailProof::add_y_n_arr(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  y_n_arr_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:safeheron.proto.PailProof.y_N_arr)
}
inline void PailProof::add_y_n_arr(const char* value, size_t size) {
  y_n_arr_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:safeheron.proto.PailProof.y_N_arr)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
PailProof::y_n_arr() const {
  // @@protoc_insertion_point(field_list:safeheron.proto.PailProof.y_N_arr)
  return y_n_arr_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>*
PailProof::mutable_y_n_arr() {
  // @@protoc_insertion_point(field_mutable_list:safeheron.proto.PailProof.y_N_arr)
  return &y_n_arr_;
}

// -------------------------------------------------------------------

// AliceRangeProof

// string z = 1;
inline void AliceRangeProof::clear_z() {
  z_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AliceRangeProof::z() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.AliceRangeProof.z)
  return z_.GetNoArena();
}
inline void AliceRangeProof::set_z(const ::std::string& value) {
  
  z_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.AliceRangeProof.z)
}
#if LANG_CXX11
inline void AliceRangeProof::set_z(::std::string&& value) {
  
  z_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.AliceRangeProof.z)
}
#endif
inline void AliceRangeProof::set_z(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  z_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.AliceRangeProof.z)
}
inline void AliceRangeProof::set_z(const char* value, size_t size) {
  
  z_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.AliceRangeProof.z)
}
inline ::std::string* AliceRangeProof::mutable_z() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.AliceRangeProof.z)
  return z_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AliceRangeProof::release_z() {
  // @@protoc_insertion_point(field_release:safeheron.proto.AliceRangeProof.z)
  
  return z_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AliceRangeProof::set_allocated_z(::std::string* z) {
  if (z != nullptr) {
    
  } else {
    
  }
  z_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), z);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.AliceRangeProof.z)
}

// string u = 2;
inline void AliceRangeProof::clear_u() {
  u_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AliceRangeProof::u() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.AliceRangeProof.u)
  return u_.GetNoArena();
}
inline void AliceRangeProof::set_u(const ::std::string& value) {
  
  u_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.AliceRangeProof.u)
}
#if LANG_CXX11
inline void AliceRangeProof::set_u(::std::string&& value) {
  
  u_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.AliceRangeProof.u)
}
#endif
inline void AliceRangeProof::set_u(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  u_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.AliceRangeProof.u)
}
inline void AliceRangeProof::set_u(const char* value, size_t size) {
  
  u_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.AliceRangeProof.u)
}
inline ::std::string* AliceRangeProof::mutable_u() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.AliceRangeProof.u)
  return u_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AliceRangeProof::release_u() {
  // @@protoc_insertion_point(field_release:safeheron.proto.AliceRangeProof.u)
  
  return u_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AliceRangeProof::set_allocated_u(::std::string* u) {
  if (u != nullptr) {
    
  } else {
    
  }
  u_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), u);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.AliceRangeProof.u)
}

// string w = 3;
inline void AliceRangeProof::clear_w() {
  w_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AliceRangeProof::w() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.AliceRangeProof.w)
  return w_.GetNoArena();
}
inline void AliceRangeProof::set_w(const ::std::string& value) {
  
  w_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.AliceRangeProof.w)
}
#if LANG_CXX11
inline void AliceRangeProof::set_w(::std::string&& value) {
  
  w_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.AliceRangeProof.w)
}
#endif
inline void AliceRangeProof::set_w(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  w_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.AliceRangeProof.w)
}
inline void AliceRangeProof::set_w(const char* value, size_t size) {
  
  w_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.AliceRangeProof.w)
}
inline ::std::string* AliceRangeProof::mutable_w() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.AliceRangeProof.w)
  return w_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AliceRangeProof::release_w() {
  // @@protoc_insertion_point(field_release:safeheron.proto.AliceRangeProof.w)
  
  return w_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AliceRangeProof::set_allocated_w(::std::string* w) {
  if (w != nullptr) {
    
  } else {
    
  }
  w_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), w);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.AliceRangeProof.w)
}

// string s = 4;
inline void AliceRangeProof::clear_s() {
  s_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AliceRangeProof::s() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.AliceRangeProof.s)
  return s_.GetNoArena();
}
inline void AliceRangeProof::set_s(const ::std::string& value) {
  
  s_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.AliceRangeProof.s)
}
#if LANG_CXX11
inline void AliceRangeProof::set_s(::std::string&& value) {
  
  s_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.AliceRangeProof.s)
}
#endif
inline void AliceRangeProof::set_s(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  s_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.AliceRangeProof.s)
}
inline void AliceRangeProof::set_s(const char* value, size_t size) {
  
  s_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.AliceRangeProof.s)
}
inline ::std::string* AliceRangeProof::mutable_s() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.AliceRangeProof.s)
  return s_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AliceRangeProof::release_s() {
  // @@protoc_insertion_point(field_release:safeheron.proto.AliceRangeProof.s)
  
  return s_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AliceRangeProof::set_allocated_s(::std::string* s) {
  if (s != nullptr) {
    
  } else {
    
  }
  s_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), s);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.AliceRangeProof.s)
}

// string s1 = 5;
inline void AliceRangeProof::clear_s1() {
  s1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AliceRangeProof::s1() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.AliceRangeProof.s1)
  return s1_.GetNoArena();
}
inline void AliceRangeProof::set_s1(const ::std::string& value) {
  
  s1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.AliceRangeProof.s1)
}
#if LANG_CXX11
inline void AliceRangeProof::set_s1(::std::string&& value) {
  
  s1_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.AliceRangeProof.s1)
}
#endif
inline void AliceRangeProof::set_s1(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  s1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.AliceRangeProof.s1)
}
inline void AliceRangeProof::set_s1(const char* value, size_t size) {
  
  s1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.AliceRangeProof.s1)
}
inline ::std::string* AliceRangeProof::mutable_s1() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.AliceRangeProof.s1)
  return s1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AliceRangeProof::release_s1() {
  // @@protoc_insertion_point(field_release:safeheron.proto.AliceRangeProof.s1)
  
  return s1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AliceRangeProof::set_allocated_s1(::std::string* s1) {
  if (s1 != nullptr) {
    
  } else {
    
  }
  s1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), s1);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.AliceRangeProof.s1)
}

// string s2 = 6;
inline void AliceRangeProof::clear_s2() {
  s2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AliceRangeProof::s2() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.AliceRangeProof.s2)
  return s2_.GetNoArena();
}
inline void AliceRangeProof::set_s2(const ::std::string& value) {
  
  s2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.AliceRangeProof.s2)
}
#if LANG_CXX11
inline void AliceRangeProof::set_s2(::std::string&& value) {
  
  s2_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.AliceRangeProof.s2)
}
#endif
inline void AliceRangeProof::set_s2(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  s2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.AliceRangeProof.s2)
}
inline void AliceRangeProof::set_s2(const char* value, size_t size) {
  
  s2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.AliceRangeProof.s2)
}
inline ::std::string* AliceRangeProof::mutable_s2() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.AliceRangeProof.s2)
  return s2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AliceRangeProof::release_s2() {
  // @@protoc_insertion_point(field_release:safeheron.proto.AliceRangeProof.s2)
  
  return s2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AliceRangeProof::set_allocated_s2(::std::string* s2) {
  if (s2 != nullptr) {
    
  } else {
    
  }
  s2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), s2);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.AliceRangeProof.s2)
}

// -------------------------------------------------------------------

// DLNProof

// repeated string alpha_arr = 1;
inline int DLNProof::alpha_arr_size() const {
  return alpha_arr_.size();
}
inline void DLNProof::clear_alpha_arr() {
  alpha_arr_.Clear();
}
inline const ::std::string& DLNProof::alpha_arr(int index) const {
  // @@protoc_insertion_point(field_get:safeheron.proto.DLNProof.alpha_arr)
  return alpha_arr_.Get(index);
}
inline ::std::string* DLNProof::mutable_alpha_arr(int index) {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.DLNProof.alpha_arr)
  return alpha_arr_.Mutable(index);
}
inline void DLNProof::set_alpha_arr(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:safeheron.proto.DLNProof.alpha_arr)
  alpha_arr_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void DLNProof::set_alpha_arr(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:safeheron.proto.DLNProof.alpha_arr)
  alpha_arr_.Mutable(index)->assign(std::move(value));
}
#endif
inline void DLNProof::set_alpha_arr(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  alpha_arr_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:safeheron.proto.DLNProof.alpha_arr)
}
inline void DLNProof::set_alpha_arr(int index, const char* value, size_t size) {
  alpha_arr_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.DLNProof.alpha_arr)
}
inline ::std::string* DLNProof::add_alpha_arr() {
  // @@protoc_insertion_point(field_add_mutable:safeheron.proto.DLNProof.alpha_arr)
  return alpha_arr_.Add();
}
inline void DLNProof::add_alpha_arr(const ::std::string& value) {
  alpha_arr_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:safeheron.proto.DLNProof.alpha_arr)
}
#if LANG_CXX11
inline void DLNProof::add_alpha_arr(::std::string&& value) {
  alpha_arr_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:safeheron.proto.DLNProof.alpha_arr)
}
#endif
inline void DLNProof::add_alpha_arr(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  alpha_arr_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:safeheron.proto.DLNProof.alpha_arr)
}
inline void DLNProof::add_alpha_arr(const char* value, size_t size) {
  alpha_arr_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:safeheron.proto.DLNProof.alpha_arr)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
DLNProof::alpha_arr() const {
  // @@protoc_insertion_point(field_list:safeheron.proto.DLNProof.alpha_arr)
  return alpha_arr_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>*
DLNProof::mutable_alpha_arr() {
  // @@protoc_insertion_point(field_mutable_list:safeheron.proto.DLNProof.alpha_arr)
  return &alpha_arr_;
}

// repeated string t_arr = 2;
inline int DLNProof::t_arr_size() const {
  return t_arr_.size();
}
inline void DLNProof::clear_t_arr() {
  t_arr_.Clear();
}
inline const ::std::string& DLNProof::t_arr(int index) const {
  // @@protoc_insertion_point(field_get:safeheron.proto.DLNProof.t_arr)
  return t_arr_.Get(index);
}
inline ::std::string* DLNProof::mutable_t_arr(int index) {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.DLNProof.t_arr)
  return t_arr_.Mutable(index);
}
inline void DLNProof::set_t_arr(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:safeheron.proto.DLNProof.t_arr)
  t_arr_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void DLNProof::set_t_arr(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:safeheron.proto.DLNProof.t_arr)
  t_arr_.Mutable(index)->assign(std::move(value));
}
#endif
inline void DLNProof::set_t_arr(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  t_arr_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:safeheron.proto.DLNProof.t_arr)
}
inline void DLNProof::set_t_arr(int index, const char* value, size_t size) {
  t_arr_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.DLNProof.t_arr)
}
inline ::std::string* DLNProof::add_t_arr() {
  // @@protoc_insertion_point(field_add_mutable:safeheron.proto.DLNProof.t_arr)
  return t_arr_.Add();
}
inline void DLNProof::add_t_arr(const ::std::string& value) {
  t_arr_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:safeheron.proto.DLNProof.t_arr)
}
#if LANG_CXX11
inline void DLNProof::add_t_arr(::std::string&& value) {
  t_arr_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:safeheron.proto.DLNProof.t_arr)
}
#endif
inline void DLNProof::add_t_arr(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  t_arr_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:safeheron.proto.DLNProof.t_arr)
}
inline void DLNProof::add_t_arr(const char* value, size_t size) {
  t_arr_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:safeheron.proto.DLNProof.t_arr)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
DLNProof::t_arr() const {
  // @@protoc_insertion_point(field_list:safeheron.proto.DLNProof.t_arr)
  return t_arr_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>*
DLNProof::mutable_t_arr() {
  // @@protoc_insertion_point(field_mutable_list:safeheron.proto.DLNProof.t_arr)
  return &t_arr_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace safeheron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_zkp_2eproto
